version: "3"

vars:
  HASH: { sh: git rev-parse --short HEAD }
  BRANCH: { sh: git rev-parse --abbrev-ref HEAD }
  BINARY_PATH: ./bin/main

tasks:
  tools:
    env:
      FILE: ".git/hooks/pre-commit"
    cmds:
      - command -v air 2>/dev/null || go install github.com/air-verse/air@v1.61.7
      - command -v mockgen 2>/dev/null || go install -v github.com/golang/mock/mockgen@v1.6.0 # v1.6.0
      - command -v golangci-lint 2>/dev/null || curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.2
      - command -v gomodifytags 2>/dev/null || go install -v github.com/fatih/gomodifytags@v1.17.0
      - command -v gotestsum 2>/dev/null || go install -v gotest.tools/gotestsum@v1.12.1
      - cp .github/pre-commit.sh $FILE
      - chmod +x $FILE
      - test -f $FILE && echo "$FILE exists."

  generate:
    cmds:
      - go generate ./...

  analysis:
    deps: [generate]
    cmds:
      - golangci-lint run --new-from-rev HEAD~ ./...

  unit_tests:
    deps: [generate]
    cmds:
      - gotestsum --format=testname --hide-summary=skipped -- -failfast -count=1 -v -race ./...

  build:
    deps: [generate]
    cmds:
      - CGO_ENABLED=0 go build -ldflags "-X main.Version={{.HASH}} -X main.Hash={{.HASH}}" -a -o {{.BINARY_PATH}} .
